apiVersion: v1
kind: Service
metadata:
  name: {{ include "ailog.fullname" . }}
  labels:
{{ include "ailog.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "ailog.selectorLabels" . | indent 4 }}
